### ISSUE TITLE
Student dasboard doesn't load if the student has no courses assigned

### ISSUE THREAD

**Issue by travisallen6** [Travis-Kyle-Tyler-Sam/infernal-piguana2#47]
`(node:54232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: req.userCourses is not iterable`
`(node:54232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: req.userCourses is not iterable`

**Comment by clawdaddy** [comment]
Fixed this issue. Views now let the user know that they aren't enrolled in any courses
